### ISSUE TITLE
pyidm doesn't start I have to start it buch of time to make it work

### ISSUE THREAD

**Issue by AliHamza-ah** [pyIDM/PyIDM#152] opened 2020-08-27 11:38 UTC
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

These are the errors I get

![pyidm issue](https://user-images.githubusercontent.com/68776282/91437935-9f800000-e838-11ea-9bc2-1620796960b1.png)

**Comment by pyIDM** [comment] 2020-08-27 13:07
@AliHamza-ah 
this issue caused by GTK 
you can fix it by disabling systray icon

you can do this by editing "PyIDM.py" file located in "current working directory path" shown in your screenshot above
you should change line 147 from

`Thread(target=systray.run, daemon=True).start()`

to

`# Thread(target=systray.run, daemon=True).start()`

then save the file and start pyidm again, it should work without a problem

**Comment by AliHamza-ah** [comment] 2020-08-27 18:32
Thanks.
That was a quick reply. :)

**Comment by Harshil783** [comment] 2020-09-09 12:15
Plz Close This Issue If It Is Solved

**Closed** 2020-09-09 12:24 UTC
Labels: bug
