### ISSUE TITLE
Doesn't run (macOS)

### ISSUE THREAD

**Issue by jromero2k** [pyIDM/PyIDM#118] opened 2020-06-20 09:26 UTC
>> Systray is not supported on mac yet
>> -------------------------------------------------- PyIDM --------------------------------------------------
>> Starting PyIDM version: 2020.6.15 Non-Frozen
>> operating system: Darwin-18.7.0-x86_64-i386-64bit - x86_64
>> current working directory: /usr/local/lib/python3.7/site-packages/pyidm
>> Load Application setting from /usr/local/lib/python3.7/site-packages/pyidm
>> setting.cfg not found
>> Load previous download items from /usr/local/lib/python3.7/site-packages/pyidm
>> downloads.cfg file not found
Traceback (most recent call last):
  File "/usr/local/bin/pyidm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pyidm/PyIDM.py", line 147, in main
    main_window = MainWindow()
  File "/usr/local/lib/python3.7/site-packages/pyidm/gui.py", line 110, in __init__
    self.setup()
  File "/usr/local/lib/python3.7/site-packages/pyidm/gui.py", line 181, in setup
    self.start_window()
  File "/usr/local/lib/python3.7/site-packages/pyidm/gui.py", line 554, in start_window
    self.window.Finalize()
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 7034, in Finalize
    self.Read(timeout=1)
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 6859, in Read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 6897, in _read
    self._Show()
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 6733, in _Show
    StartupTK(self)
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 11086, in StartupTK
    ConvertFlexToTK(my_flex_form)
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 10988, in ConvertFlexToTK
    PackFormIntoFrame(MyFlexForm, master, MyFlexForm)
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 10585, in PackFormIntoFrame
    PackFormIntoFrame(element, toplevel_form.TKroot, toplevel_form)
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 10525, in PackFormIntoFrame
    PackFormIntoFrame(element, element.TKFrame, toplevel_form)
  File "/usr/local/lib/python3.7/site-packages/PySimpleGUI/PySimpleGUI.py", line 10367, in PackFormIntoFrame
    photo = tk.PhotoImage(data=element.Data)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize image data

**Comment by pyIDM** [comment] 2020-06-20 09:39
@jromero2k 
This is related to Tkinter 8.5 can't recognize buttons icons: 
as mentioned in "python.org" the Apple-supplied Tcl/Tk 8.5 has serious bugs that can cause application crashes. If you wish to use Tkinter, do not use the Apple-supplied Pythons. Instead, install and use a newer version of Python from python.org or a third-party distributor that supplies or links with a newer version of Tcl/Tk. full article here https://www.python.org/download/mac/tcltk/

for detailed fixes refer to issue #113 

I already added this note in readme file

**Comment by jromero2k** [comment] 2020-06-20 09:53
This Python3 was installed the standard way, `brew install python`

```
$ brew info python
python: stable 3.7.7 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python/3.7.6_1 (4,051 files, 61.9MB) *
```

According to python.org, it shouldn't require an external Tcl/Tk

**Comment by jromero2k** [comment] 2020-06-20 09:56
### built-in 8.6.8
As of Python 3.7.0, 3.6.8, and 2.7.16, all current Python installers for macOS downloadable from python.org supply their own private copies of Tcl/Tk 8.6.8. They do not look for or use any third-party or system copies of Tcl/Tk. This is an Aqua Cocoa Tk.

**Comment by pyIDM** [comment] 2020-06-20 10:22
Please use this in terminal to verify your tkinter version
`python3 -c "import tkinter; print(tkinter.TkVersion);"`

If it report 8.6, you are good to go.

this is quoted from issue #113 

> Fixed in official python.org 64-bit (only) installer for OS X. Tk version 8.6 is included >out of the box. Warning: if you use homebrew, as of this post doing brew install python3 >will only give you 8.5, and 8.6 is required to use png so you'll have to use official >installer instead. To check which Tk you are using:
$ python3 -c 'import tkinter; print(tkinter.TkVersion);'
If it report 8.6, you are good to go.

**Comment by jromero2k** [comment] 2020-06-20 20:07
Indeed, the result is `8.5`. I'll have to wait until Homebrew fixes their Python

**Comment by pyIDM** [comment] 2020-06-21 06:50
> Indeed, the result is `8.5`. I'll have to wait until Homebrew fixes their Python

I am not sure if they have the will to fix it, the installed python thru homebrew will continue to use tkinter version supplied by Apple
here is an issue opened in homebrew official repo 
https://github.com/Homebrew/brew/issues/6357

the only fix is to use python installers from "python.org" website

https://www.python.org/download/mac/tcltk/

> If you are using a Python from any current python.org Python installer for macOS (3.8.0+, 3.7.2+, 3.6.8, or 2.7.16+), no further action is needed to use IDLE or tkinter. A built-in version of Tcl/Tk 8.6 will be used.

will close this issue as the problem is not related to PyIDM source code

**Closed by pyIDM** 2020-06-21 06:50 UTC
