### ISSUE TITLE
No such thing as atk.Radiobutton

### ISSUE THREAD

**Issue by bertaga** [pyIDM/PyIDM#188] opened 2020-11-12 15:39 UTC
```Python
Traceback (most recent call last):
  File "/usr/bin/pyidm", line 33, in <module>
    sys.exit(load_entry_point('PyIDM==2020.11.10', 'console_scripts', 'pyidm')())
  File "/usr/lib/python3.8/site-packages/pyidm/PyIDM.py", line 39, in main
    c = Controller(view_class=MainWindow)
  File "/usr/lib/python3.8/site-packages/pyidm/controller.py", line 138, in __init__
    self.view = view_class(controller=self)
  File "/usr/lib/python3.8/site-packages/pyidm/tkview.py", line 2525, in __init__
    self.create_main_widgets()
  File "/usr/lib/python3.8/site-packages/pyidm/tkview.py", line 2652, in create_main_widgets
    self.sett_frame = self.create_settings_tab()
  File "/usr/lib/python3.8/site-packages/pyidm/tkview.py", line 2837, in create_settings_tab
    proxy_type_option('http')
  File "/usr/lib/python3.8/site-packages/pyidm/tkview.py", line 2834, in proxy_type_option
    atk.Radiobutton(proxy_frame, text=text, value=text, variable=self.proxy_type_var, bg=bg,
AttributeError: module 'awesometkinter' has no attribute 'Radiobutton'
```
A simple fix is to change the calls to `atk.Radiobutton()` by `atk.button.Radiobutton()`

**Comment by bertaga** [comment] 2020-11-12 15:49
#189

**Comment by pyIDM** [comment] 2020-11-12 21:17
@bertaga 
Thanks, your fix already merged, 
the strange thing is i can't reproduce the same error on my machine with python 3.8 as yours

can you please do some tests on awesometkinter files

navigate to awesometkinter folder (you can get installation folder by running the following command: `python -m pip show  awesometkinter`)

then open button.py file and modify the last line by adding double underscore to the word "all", i.e.  replacing 
`all = ['Button3d', 'RadioButton']`

to:

`__all__ = ['Button3d', 'RadioButton']`

save changes and try to run pyidm without your fix and see if this is the main cause in awesometkinter module

another suggestion is to change awesometkinter __init__.py file line 11 to: `from .button import Radiobutton, Button3d`

**Closed** 2020-11-14 14:41 UTC
